### PR TITLE
Bug fixes in Table and Title

### PR DESCRIPTION
**Pull request by l-k-**
Table:
- if text doesn't fit in column, trim it and add ellipses;
- use react-bootstrap to make tooltips in header show up immediately.

Title:
- ‘remove' button for site;
- site selection dropdown.

### CODE REVIEW

**Comment by l-k-** [comment]
I'll add the dropdown to the table view -- doing it now

**Comment by l-k-** [comment]
I'll add something for table/field navigation next.

**Comment by bruth** [comment]
Looking better! However I found this:
screen shot 2015-11-12 at 10 35 28 am

**Comment by l-k-** [comment]
Whoa. Thanks. What url got you there? I can't reproduce it for some reason.

**Comment by bruth** [comment]
http://localhost:8125/models/pedsnet/2.0.0/provider/dqa/Nationwide

**Comment by l-k-** [comment]
ooooh I know what it is. You need the new version of DQA service for the new header to work correctly. 
But still, this is a bug, I will fix it. Thanks.

**Comment by l-k-** [comment]
fixed, thanks

**Comment by bruth** [comment]
Looks good, please squash.

**Pull request merged**
