### PR TITLE
Change to a full page layout, hierarchical navigation

### PR DESCRIPTION
**Pull request by l-k-**
Improved per-site DQA reports.

### CODE REVIEW

**Comment by bruth** [comment]
Nice job, definitely an improvement! Here are some things some things to fix or improve. You can evaluate it to see how much time they will take and whether we should defer them for later. I will have to review the field-level DQA pages once the updates to the service are deployed.
- Remove search link from header since it is not yet implemented. This is just so users don't expect it to be working.
- Navigation flickers when it changes. I know React does not unnecessarily remove or add DOM nodes if it does not need to, but rather updates in place. The flicker indicates that the nodes are being removed somehow.

nav-flicker
- Remove `v.` prefix from name:

screen shot 2015-10-27 at 6 32 21 am
- Move tabs under page context. I am going take a pass at this along with the breadcrumbs.

move-nav
- Add description to field pages. I noticed this for the fields that don't have any content.

screen shot 2015-10-27 at 6 55 09 am
- Fix horizontal overflow for content boxes

screen shot 2015-10-27 at 6 56 28 am

**Comment by bruth** [comment]
Another subtle fix is to cancel propagation of the click event so the `#` doesn't appear in the URL. The unwanted result is needing to hit the back button twice to return to the previous page.

redundant-link

**Comment by bruth** [comment]
> I am going take a pass at this along with the breadcrumbs.

I take that back for now since it may conflict with some of the other changes you need to make.

**Comment by bruth** [comment]
I am updating DQA service. Will check the UI shortly.

**Comment by l-k-** [comment]
Sounds good. I'm working on the tabs / breadcrumbs. Thanks for the reviews!

**Comment by bruth** [comment]
Regarding the navigation, I think it would be better to render the links in a disabled state and enable them if the data is available. The constantly changing navigation across fields or tables is a bit confusing.

**Comment by l-k-** [comment]
oooh that's a good idea.

**Comment by l-k-** [comment]
I think I addressed all the issues.
(But I'll try to think of a better wording for the table/field title since it does look odd)
Thanks for the feedback!

**Pull request merged**
