### PR TITLE
Prepend root path to css and js links in index

### PR DESCRIPTION
**Pull request by gracecodes144**
Signed-off-by: Aaron Browne aaron0browne@gmail.com

### CODE REVIEW

**Comment by bruth** [comment]
The paths should be constructed in the `render()` function using `env.root` and set in the HTML. The `entrypoint.sh` script is reserved for setting configuration options.

**Comment by gracecodes144** [comment]
OK, closing and removing.

**Comment by l-k-** [comment]
But this is for style sheets: 
https://github.com/PEDSnet/pedsnet-catalogue/blob/master/src/html/index.html#L10-L13
and these js sources:
https://github.com/PEDSnet/pedsnet-catalogue/blob/master/src/html/index.html#L31-L32

I can't figure out where I can set these besides index.html. I'll try to figure it out.

**Comment by bruth** [comment]
@aaron0browne I misread the change.

**Comment by bruth** [comment]
The nginx config needs to be adapted as well..

**Comment by gracecodes144** [comment]
OK, great, so the only thing left, I think, is the two hard-coded absolute references in the header.

**Pull request merged**
